---
# vim:ff=unix ts=2 sw=2 ai sts=1 expandtab

- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: ensure user account exists
  user: name='{{user}}'
