---
# vim:ff=unix ts=2 sw=2 ai sts=1 expandtab
-
  hosts: osmdb
  remote_user: vagrant
  vars:
    database_name: osm
    database_user: osm 

  roles:      
    - { role: postgis, database_name: '{{database_name}}', database_user: '{{database_user}}' }

  handlers:
   - name: restart postgresql
     action: service name=postgresql state=restarted 
